### ISSUE TITLE
US and/or metric units?

### ISSUE THREAD

**Issue by lemonad** [coding-horror/basic-computer-games#172]
I noticed that the units used are miles/hour, ft/sec^2, which makes perfect/no sense depending on where you grow up. Should we keep these to be true to the original or should we try to cater to both worlds?

I can't say I remember this as a problem as a kid but anyway : )

**Comment by gcarreno** [comment]
My 2&cent;: Officially all of the science world is using metric and that includes all imperial using countries.
Imperial measures are still around because of the obstinate older people that didn't grew up with metric and the fact that those governments haven't made road signs metric.
I vote metric, but hey, I'm Portuguese and metric just makes sense to me :stuck_out_tongue_closed_eyes:

**Comment by lemonad** [comment]
I'm Swedish so I'm also slightly biased towards metric units : )

**Comment by gcarreno** [comment]
> I'm Swedish so I'm also slightly biased towards metric units : )

&lt;sarcasm&gt; Congratulations your opinion matters so much to us, keep it up  LOL!!! :stuck_out_tongue_closed_eyes: 

Imagine measurements being defined by the kings body parts... **PREPOSTEROUS!!!!** &lt;/sarcasm&gt;

Joking aside, metric rulez, @ me :stuck_out_tongue:

**Comment by coding-horror** [comment]
I hear you and agree, but I think on this issue (metric vs imperial units) we should leave as-is for historical reasons.

**Comment by lemonad** [comment]
@coding-horror Makes sense. Should I close the issue or leave it open for others to chime in?

**Comment by coding-horror** [comment]
Thanks for bringing this to our attention! I'll go ahead and close it.
