### ISSUE TITLE
Straight port or reimplement?

### ISSUE THREAD

**Issue by markyocom** [coding-horror/basic-computer-games#231]
This looks to be a fun project (I remember these books fondly!).

Looking at some of the conversions already added, I'm questioning whether we should be converting these to other languages literally as close as possible to the BASIC versions or is it more like "implement Acey Ducey with the same simple _behavior_ as the original, in various languages"?  There are some uploads that look like they're trying to keep the BASIC behavior (close to line for line) even though it's not how things would often be done in the new target language if it were being written from scratch.

As an example (and not meaning to single this particular one out, it's the first one I found), the Perl implementation of Buzzword keeps the look and feel of the original code with all caps text and uses short variable names and hardcoded array lengths based on (the human) having counted the items in the list ahead of time.  That's a very straightforward port from BASIC to Perl, but it's not how it would probably be written from scratch.  From scratch, I'm guessing most people would use lowercase in the text (and probably in the variable names) and dynamically determine the number of elements in the array when choosing a random element (or use a built-in module to do it rather than rolling their own).  In modern languages, those would be a best practices.

Which way would you prefer?  I'm (obviously 😊) partial to "re-implement" over "port it straight" in the interest of teaching new programmers, but I'll defer to you.

**Comment by blaze-lambda** [comment]
I'm not a maintainer here, but I've been porting some of them.

My plan was to do a fairly literal conversion of all of them as a first pass.  If I had time, I was hoping to do more "idiomatic" versions.  Then leave them both in the repo, with a note at the top describing the coding style.  In doing my translations, I have found having both styles available in other languages helps me comprehend the code.

In the "Amazing" example, having the Javascript version, which is more literal, made untangling the GOTO mess easier--but didn't give much insight into the logic of drawing the maze.  I've already noticed some idioms in the original BASIC--used to get around the language limitations--that could be written up into the documentation of this project to help others.

One advantage to preserving the external behaviour of the program (including case, formatting, etc.) would be for testing, perhaps with a tool like Expect (since these are mostly text games).

Mostly I think this project is just for fun--so a general rule might be "Do what you think is fun."?

My $0.02

**Comment by coding-horror** [comment]
Sure! But I'd add a caveat with "fun", the idea is to teach good programming practices in the target language as well -- and illustrate how far we've come since the late 1970s in programming!

**Comment by blaze-lambda** [comment]
I also re-read the top level README.md.  The [project goals](https://github.com/coding-horror/basic-computer-games#project-goals) section did provide good general guidelines on this issue.  Obviously the code needs to be better than 70's unstructured basic, but also somewhat less complicated than using every feature of C++17.  I think it will still be fun somewhere in-between the two.

**Comment by coding-horror** [comment]
Just to address the specifics

- we definitely want both upper and lower case support (no need to PRESERVE ALL CAPS
- using reasonable variable names instead of single letters is certainly OK
- using modern language features (not SUPER cutting edge brand new, but say at least 5 years old) is fine

So to answer your question, **preserve the general behavior**, we aren't looking for a carbon copy, we want to modernize the code as we go.
